In [1]:
import numpy as np
import random

## 题目一 简单编程题（numpy数组的创建和性质）

### 1、创建一个4*6的二维数组，元素由0~1之间均匀分布的随机数构成，输出其形状、大小、维度和数据类型。

In [2]:
arr = np.random.random((4, 6))
print(arr)
print("shape = {}, size = {}, dimension = {}, dtype = {}"
      .format((arr.shape[0], arr.shape[1]), arr.size, arr.ndim, arr.dtype))

[[0.87234165 0.76793816 0.20329659 0.67588528 0.39278516 0.30852181]
 [0.3722015  0.17675793 0.01827887 0.33450565 0.22872758 0.35906343]
 [0.4448989  0.0355992  0.88128631 0.40998858 0.31613782 0.61468709]
 [0.80893753 0.20962329 0.84701968 0.61099015 0.50922118 0.65357641]]
shape = (4, 6), size = 24, dimension = 2, dtype = float64


### 2、将（1）中的二维数组分别转换为3*8的数组和摊平为一维数组。

In [3]:
print(arr.reshape(3, 8))

[[0.87234165 0.76793816 0.20329659 0.67588528 0.39278516 0.30852181
  0.3722015  0.17675793]
 [0.01827887 0.33450565 0.22872758 0.35906343 0.4448989  0.0355992
  0.88128631 0.40998858]
 [0.31613782 0.61468709 0.80893753 0.20962329 0.84701968 0.61099015
  0.50922118 0.65357641]]


In [4]:
print(arr.reshape(-1))

[0.87234165 0.76793816 0.20329659 0.67588528 0.39278516 0.30852181
 0.3722015  0.17675793 0.01827887 0.33450565 0.22872758 0.35906343
 0.4448989  0.0355992  0.88128631 0.40998858 0.31613782 0.61468709
 0.80893753 0.20962329 0.84701968 0.61099015 0.50922118 0.65357641]


### 3、创建2个4*4的二维数组，元素为整数，随机取自区间[0, 10)，请将两个数组分别进行水平拼接和垂直拼接。

In [5]:
arr2 = np.random.randint(0, 10, (4, 4))
arr3 = np.random.randint(0, 10, (4, 4))
print("arr2 = \n{}".format(arr2))
print("arr3 = \n{}".format(arr3))

arr2 = 
[[9 5 7 7]
 [2 5 2 9]
 [8 7 4 0]
 [4 1 5 3]]
arr3 = 
[[9 0 5 1]
 [2 0 2 1]
 [5 5 5 1]
 [4 6 1 6]]


In [6]:
# 水平拼接
print(np.hstack([arr2, arr3]))
# 垂直拼接
print("\n")
print(np.vstack([arr2, arr3]))

[[9 5 7 7 9 0 5 1]
 [2 5 2 9 2 0 2 1]
 [8 7 4 0 5 5 5 1]
 [4 1 5 3 4 6 1 6]]


[[9 5 7 7]
 [2 5 2 9]
 [8 7 4 0]
 [4 1 5 3]
 [9 0 5 1]
 [2 0 2 1]
 [5 5 5 1]
 [4 6 1 6]]


### 4、创建一个16*16的数组，其中，数组的外围均为1，内部均为0，提示：用到切片赋值。

In [11]:
arr4 = np.zeros((16, 16))
# print(arr4)
arr4[0] = 1
arr4[:, 0] = 1
arr4[arr4.shape[0] - 1] = 1
arr4[:, arr4.shape[1] - 1] = 1
print(arr4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 题目二 简单编程题（numpy四大运算和通用函数）

### 5、创建一个由10000个元素构成的一维数组，元素随机取自[0, 100)
 求数组元素的均值、方差和标准差；

 通过 (x-x.mean)/x.std的方法，将数组归一化。

 求数组的最大值和最小值，并获取其索引位置；

 通过 (x-x.min)/(x.max-x.min)的方法，将数组归一化。

In [12]:
arr5 = np.random.randint(0, 100, 10000)

In [13]:
print(arr5)

[30 78 43 ... 39 99 11]


In [14]:
print("均值 = {}, 方差 = {}, 标准差 = {}".format(arr5.mean(), arr5.var(), arr5.std()))

均值 = 49.5523, 方差 = 830.88746471, 标准差 = 28.82511864173329


In [15]:
print((arr5 - arr5.mean()) / arr5.std())

[-0.6783077   0.98690661 -0.22731216 ... -0.36608002  1.71543787
 -1.33745503]


In [16]:
# 最大值
print(arr5.max(), arr5.argmax())
# 最小值
print(arr5.min(), arr5.argmin())

99 190
0 34


In [17]:
print((arr5 - arr5.min()) / (arr5.max() - arr5.min()))

[0.3030303  0.78787879 0.43434343 ... 0.39393939 1.         0.11111111]


### 6、创建一个由30个元素构成的一维数组，元素随机取自[80, 100)
 获得大于等于95分的成绩；

 获得小于等于85分的成绩；

 获得大于85分，小于95分的成绩；

 对成绩进行排序。

In [18]:
score = np.random.randint(80, 100, 30)
print(score)

[89 90 97 96 83 97 92 82 98 90 86 99 94 98 98 91 91 85 98 81 98 82 86 84
 89 98 98 98 95 87]


In [19]:
print(score[score >= 95])
print(score[score <= 85])

[97 96 97 98 99 98 98 98 98 98 98 98 95]
[83 82 85 81 82 84]


In [22]:
score_over_85 = score[score > 85]
print(score_over_85[score_over_85 < 95])
# print(score[score > 85 and score < 95]) 

[89 90 92 90 86 94 91 91 86 89 87]


In [23]:
print(np.sort(score))

[81 82 82 83 84 85 86 86 87 89 89 90 90 91 91 92 94 95 96 97 97 98 98 98
 98 98 98 98 98 99]


### 7、构建两个3*3的二维列表A和B
（1）乘法运算

 用Python for循环实现A*B的乘法运算；

 用Numpy 实现A*B 的乘法运算；

 对比两种实现方式的运行时间。

（2）矩阵乘法

 用Python for循环实现A和B的矩阵乘法；

 用Numpy实现np.dot(A, B)的矩阵乘法；

 对比两种实现方式的运行时间。

（3）对比矩阵乘法跟乘法运算的不同。

In [24]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[3, 4, 8], [5, 2, 1], [4, 5, 9]]
print(A, B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] [[3, 4, 8], [5, 2, 1], [4, 5, 9]]


In [26]:
# 乘法运算
import time

start_time = time.time()
for i in range(len(A)):
        for j  in range(len(B)):
            A[i][j] = A[i][j] * B[i][j]
end_time = time.time()                

print(start_time, end_time)
print("A = {}, the cost time is {}ms".format(A, (end_time - start_time) * 1000))

1571993538.380726 1571993538.381723
A = [[9, 32, 192], [100, 20, 6], [112, 200, 729]], the cost time is 0.9968280792236328ms


In [27]:
A = np.array(A)
B = np.array(B)

In [28]:
%timeit (A * B)

525 ns ± 29.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
# 矩阵乘法
%timeit A.dot(B)

960 ns ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
A.dot(B)

array([[ 955, 1060, 1832],
       [ 424,  470,  874],
       [4252, 4493, 7657]])

In [31]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[3, 4, 8], [5, 2, 1], [4, 5, 9]]

In [32]:
def pro():
    res = [[0] * len(B[0]) for i in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                res[i][j] += A[i][k] * B[k][j]
    return res

In [33]:
%timeit pro()

12.7 µs ± 83.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
